import Head from 'next/head'
import { motion } from "framer-motion"
import MainLayout from '@/components/layouts/MainLayout'
import Main from '@/components/main/Main'



type Props = {}

export default function Home({ }: Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="  dark:text-gray-400 scrollbar-hide max-h-screen max-w-screen overflow-auto"
    >
      <Head>
        <title>Dave&apos;s Epic Games Rebuild</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className=''>
        <MainLayout>
          <Main/>
        </MainLayout>
      </main>
    </motion.div>
  )
}
